# Generated by Django 5.0.14 on 2025-07-11 10:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0004_alter_attendance_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveManagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "leavetype",
                    models.CharField(
                        choices=[
                            ("sick", "Sick Leave"),
                            ("casual", "Casual Leave"),
                            ("emergency", "Emergency Leave"),
                            ("study", "Study Leave"),
                        ],
                        default="sick",
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="add additional information for leave",
                        max_length=255,
                        null=True,
                        verbose_name="Reason for Leave",
                    ),
                ),
                (
                    "defaultdays",
                    models.PositiveIntegerField(
                        blank=True,
                        default=30,
                        null=True,
                        verbose_name="Leave days per year counter",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "employee_id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave",
                "verbose_name_plural": "Leaves",
                "ordering": ["-created"],
            },
        ),
    ]
