# Generated by Django 5.0.14 on 2025-05-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_dob_employee_hire_date_employee_sex_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveManagement',
        ),
    ]
