# Generated by Django 5.0.14 on 2025-07-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_delete_leavemanagement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("Present", "Present"),
                    ("Absent", "Absent"),
                    ("Leave", "Leave"),
                ],
                max_length=10,
            ),
        ),
    ]
